<?xml version="1.0"?>
<package format="2">
  <name>medical_robot</name>
  <version>0.1.0</version>
  <description>智慧医运机器人比赛功能包</description>
  <maintainer email="azccjl@users.noreply.github.com">azccjl</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>rospy</depend>
  <depend>std_msgs</depend>
</package>
